# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/BRAM8K/BRAM8K.xci
# IP: The module: 'BRAM8K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/BRAM8K/BRAM8K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM8K'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/BRAM8K/BRAM8K.xci
# IP: The module: 'BRAM8K' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/BRAM8K/BRAM8K_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM8K'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
