# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer4/weightRomLayer4.xci
# IP: The module: 'weightRomLayer4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer4/weightRomLayer4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weightRomLayer4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer4/weightRomLayer4.xci
# IP: The module: 'weightRomLayer4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/GradeFour/AICHIP/ref/project/repo/FinalPro-CnnAcc/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer4/weightRomLayer4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weightRomLayer4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
