# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/course/Grade2_Autumn/FPGA/final-project/new/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer7/weightRomLayer7.xci
# IP: The module: 'weightRomLayer7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/course/Grade2_Autumn/FPGA/final-project/new/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer7/weightRomLayer7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weightRomLayer7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/OneDrive/course/Grade2_Autumn/FPGA/final-project/new/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer7/weightRomLayer7.xci
# IP: The module: 'weightRomLayer7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/course/Grade2_Autumn/FPGA/final-project/new/pro/finalAcc/finalAcc.srcs/sources_1/ip/weightRomLayer7/weightRomLayer7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'weightRomLayer7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
